language: python
python: ["2.7", "3.2", "3.3"]
branches:
  only:
    - master
# command to install dependencies
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install pytest-xdist --use-mirrors
# command to run tests
script: make test PYTESTOPTS="--tb=short -n 10"
#notifications:
#  email: false
